spring:
   profiles:
      active:
        - beta
---

spring:
  profiles: beta
  application:
      name: travel-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: pyc
    password: pyc.0907
    url: jdbc:mysql://39.101.129.133:3306/db_travel?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
